### ISSUE TITLE
If QuickHub opened without internet connection, GitHub data never fetched

### ISSUE THREAD

**Issue by clacote** [chamerling/QuickHubApp#1]
In QuickHub, I've entered my GitHub username/password in Preferences. "Open at startup" is also checked.
If I boot without an active Internet connection, QuickHub is opened without GitHub data : empty menus "repositories", "issues", etc... It's obviously normal without internet connection.

If I then connect to Internet, those data are not fetched by QuickHub : I have to restart QuickHub it to make it appear.

**Comment by chamerling** [comment]
True. I am working on Internet connection issues and add this to my list. Should be in the v1.1 to be pushed to the store next week

**Comment by chamerling** [comment]
Fixed in 1.1 just submitted
