### ISSUE TITLE
Notification center Support

### ISSUE THREAD

**Issue by mlabod** [chamerling/QuickHubApp#20]
To support mountain lions native notification center would be really awesome

**Comment by chamerling** [comment]
This is planned :) Thinking about pushing out growl...

**Comment by mlabod** [comment]
nice :)

**Comment by chamerling** [comment]
@mlabod currently working on it. Will be in the next version to be released soon!

**Comment by YesThatAllen** [comment]
me too! Great app!

**Comment by chamerling** [comment]
Will fix several things, hope to push the new version out before Christmas...
