### ISSUE TITLE
App authorization to add new github account leads to 404 page

### ISSUE THREAD

**Issue by mortik** [chamerling/QuickHubApp#32]
http://quickhubapp.com/oauth.html

**Comment by chamerling** [comment]
Thanks! Going to fix that. Probably due to recent github page change!

**Comment by chamerling** [comment]
Hi @mortik,

While waiting for DNS sync, you can directly browse http://quickhubapp.herokuapp.com and follow instructions.

**Comment by chamerling** [comment]
quickhubapp.com is back!
