### ISSUE TITLE
Gists menu content not refreshed after Gist creation 

### ISSUE THREAD

**Issue by clacote** [chamerling/QuickHubApp#5]
Through QuickHub 1.1 menu "Gists/Create", I create a new Gist, and save it as Public. Creation went fine.
Then, I reopen the same menu Gists/Create : the newly created Gist isn't showed.

**Comment by chamerling** [comment]
It is not showed in the list? Normally, after a creation you should have a growl notification saying that a new gist has been created. Then the gist list is updated with the server data so you should have another notification. If not there are several reasons : On the quickhub code or on the server side code if the request is too fast and so github can not send back the updated list.
I just tested and it works here, will have a deeper look to that, thanks

**Comment by chamerling** [comment]
OK, in fact do you mean that if you open again the create window after creation, you want to have it filled with the last gist you created?

**Comment by clacote** [comment]
I mean that after a gist creation, the newly created gist is not showed in the "Gists" menu list (unless I quit and restart QuickHub).

I must say :
- I didn't have Growl application installed.
- I'm currently on a bad Wifi connection.

A detailled walkthrough of what happen :
- Clic on menu "Gists/Create".
- The "Create Gist" window shows up.
- I fill Description, File name and content fields.
- I clic on "Create Public" button. It remains clicked for a while with the spinner cursor, then goes back to normal.
- The "Create window" is still opened, with my recently typed gist content.
- I open the "Gists" menu : the newly created Gist isn't showed in the list.
- If I open Github website, I can check that the Gist has been successfully created (listed on https://gist.github.com/mine)
- Even if I wait for a while, the newly created Gist still isn't showed in the menu list.
- If I quit QuickHub, and restart it, the newly created Gist is showed in the menu list.

I then installed Growl, and enabled it.

If I now go through the same walkthrough :
- Clic on menu "Gists/Create".
- The "Create Gist" window shows up.
- I fill Description, File name and content fields.
- I clic on "Create Public" button. It remains clicked for a while with the spinner cursor, then goes back to normal.
- Two Growl notifications appear : "Gist created", and "New Gist".
- The "Create window" is still opened, with my recently typed gist content.
- I open the "Gists" menu : the newly created Gist is successfully showed in the list.

So, it seems that without Growl installed, QuickHub is not successfully refreshed.

**Comment by chamerling** [comment]
OK thanks, I will look at the code and see what happens when growl is not here, looks like there is a problem in the notification center I use.

**Comment by chamerling** [comment]
Do you remember if other menus were updated periodically when you did not have growl installed?

**Comment by clacote** [comment]
Hmm... can't be sure, sorry.
By the way, kudos for your reactivity, and thanks for this app!

**Comment by chamerling** [comment]
Fixed in 1.2
