### ISSUE TITLE
Create Issue

### ISSUE THREAD

**Issue by fabioruxo** [chamerling/QuickHubApp#7]
It would be really useful to have a "Create..." menu item on Issues opening up a panel similar to the one you use to add a Gist

**Comment by fabioruxo** [comment]
Sorry I could not label it as feature request

**Comment by chamerling** [comment]
@objectivesheep you are right, just checked the API and it will be quite easy to add.
So I will add the 'Create' item in the issue menu with a list of own repositories at first. Next I will see how I can integrate the issue management with more repositories i.e. creating issues for others repositories than ourselves. This can be done on the watched menu for example.

**Comment by fabioruxo** [comment]
Sounds great. Thanks

**Comment by chamerling** [comment]
Feature almost done, need to fix some stuff and I will publish the new version next week to the App store.

**Comment by fabioruxo** [comment]
That's great news! Thanks

**Comment by chamerling** [comment]
Implementation done. Will be part of 1.4.
