### ISSUE TITLE
Issues by Repository

### ISSUE THREAD

**Issue by fabioruxo** [chamerling/QuickHubApp#8]
It would be useful to have the issues in the issues submenu divided into issues by repository. This should be simple and you could use a separator with title to graphically show they belong to a certain repo. Repos could be alphabetically ordered for example. Just my 2 cents. Couldn't label it as Feature request.

**Comment by chamerling** [comment]
+1 will add at least in the first time tooltips and repository names in the item + more control on issues per repository

**Comment by chamerling** [comment]
Here is a workaround implemented and described in issue #11
